version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    ports:
      - 6380:6379
    volumes:
      - ./redisdata:/data
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5430:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  